import 'package:flutter/material.dart';
import 'product.dart';

// Kategori Khas Toko Sembako, Kelontong & Madura
final List<Category> sampleCategories = const [
  Category(id: 'all', name: 'Semua', icon: Icons.grid_view_rounded, color: Color(0xFF0D9488)),
  Category(id: 'sembako', name: 'Beras & Sembako', icon: Icons.rice_bowl_rounded, color: Color(0xFFF59E0B)),
  Category(id: 'mie_makanan', name: 'Mie & Makanan', icon: Icons.ramen_dining_rounded, color: Color(0xFFEA580C)),
  Category(id: 'minuman', name: 'Minuman Dingin', icon: Icons.local_drink_rounded, color: Color(0xFF06B6D4)),
  Category(id: 'bumbu', name: 'Bumbu Dapur', icon: Icons.soup_kitchen_rounded, color: Color(0xFF10B981)),
  Category(id: 'rokok', name: 'Rokok & Tembakau', icon: Icons.smoking_rooms_rounded, color: Color(0xFFEF4444)),
  Category(id: 'sabun_rumah', name: 'Sabun & Cuci', icon: Icons.cleaning_services_rounded, color: Color(0xFF6366F1)),
  Category(id: 'gas_galon', name: 'Gas LPG & Galon', icon: Icons.propane_tank_rounded, color: Color(0xFF0284C7)),
];

// Data Produk Realistis Toko Sembako / Kelontong / Madura 24 Jam
final List<Product> sampleProducts = const [
  // SEMBAKO
  Product(
    id: 'sbk-01',
    name: 'Beras Ramos Setra Pulen 5kg',
    price: 72000,
    wholesalePrice: 70000,
    wholesaleMinQty: 5,
    unit: 'sak',
    categoryId: 'sembako',
    icon: Icons.rice_bowl_rounded,
    color: Color(0xFFF59E0B),
    code: '8991001',
    stock: 40,
    description: 'Beras putih pulen wangi kualitas super kemasan karung 5kg.',
  ),
  Product(
    id: 'sbk-02',
    name: 'Beras Pandan Wangi Curah 1kg',
    price: 15000,
    wholesalePrice: 14000,
    wholesaleMinQty: 10,
    unit: 'kg',
    categoryId: 'sembako',
    icon: Icons.grain_rounded,
    color: Color(0xFFF59E0B),
    code: '8991002',
    stock: 120,
    description: 'Beras pulen wangi timbangan ecer per kilogram.',
  ),
  Product(
    id: 'sbk-03',
    name: 'Minyak Goreng Bimoli 2 Liter Pouch',
    price: 36000,
    wholesalePrice: 34500,
    wholesaleMinQty: 6,
    unit: 'pouch',
    categoryId: 'sembako',
    icon: Icons.water_drop_rounded,
    color: Color(0xFFF59E0B),
    code: '8991003',
    stock: 50,
    description: 'Minyak goreng sawit jernih kemasan pouch 2000ml.',
  ),
  Product(
    id: 'sbk-04',
    name: 'Minyak Goreng Kita 1 Liter Pouch',
    price: 16500,
    wholesalePrice: 15500,
    wholesaleMinQty: 12,
    unit: 'pouch',
    categoryId: 'sembako',
    icon: Icons.opacity_rounded,
    color: Color(0xFFF59E0B),
    code: '8991004',
    stock: 80,
    description: 'Minyak goreng subsidi Minyakita 1000ml.',
  ),
  Product(
    id: 'sbk-05',
    name: 'Telur Ayam Negeri Fresh (1 Kg)',
    price: 28000,
    wholesalePrice: 26500,
    wholesaleMinQty: 10,
    unit: 'kg',
    categoryId: 'sembako',
    icon: Icons.egg_rounded,
    color: Color(0xFFF59E0B),
    code: '8991005',
    stock: 65,
    description: 'Telur ayam negeri segar pilihan (isi ~16 butir per kg).',
  ),
  Product(
    id: 'sbk-06',
    name: 'Gula Pasir Gulaku Kuning Premium 1kg',
    price: 17500,
    wholesalePrice: 16800,
    wholesaleMinQty: 10,
    unit: 'kg',
    categoryId: 'sembako',
    icon: Icons.cookie_rounded,
    color: Color(0xFFF59E0B),
    code: '8991006',
    stock: 45,
    description: 'Gula tebu murni kemasan 1000 gram.',
  ),
  Product(
    id: 'sbk-07',
    name: 'Tepung Terigu Segitiga Biru 1kg',
    price: 12500,
    wholesalePrice: 11800,
    wholesaleMinQty: 10,
    unit: 'kg',
    categoryId: 'sembako',
    icon: Icons.bakery_dining_rounded,
    color: Color(0xFFF59E0B),
    code: '8991007',
    stock: 35,
    description: 'Tepung terigu serbaguna Bogasari 1kg.',
  ),

  // MIE INSTAN & MAKANAN
  Product(
    id: 'mie-01',
    name: 'Indomie Goreng Original 85g',
    price: 3500,
    wholesalePrice: 3200,
    wholesaleMinQty: 5,
    unit: 'bks',
    categoryId: 'mie_makanan',
    icon: Icons.ramen_dining_rounded,
    color: Color(0xFFEA580C),
    code: '8998866',
    stock: 240,
    description: 'Mie instan goreng favorit nusantara. 1 Dus isi 40 bks.',
  ),
  Product(
    id: 'mie-02',
    name: 'Indomie Kuah Soto Mie 70g',
    price: 3500,
    wholesalePrice: 3200,
    wholesaleMinQty: 5,
    unit: 'bks',
    categoryId: 'mie_makanan',
    icon: Icons.soup_kitchen_rounded,
    color: Color(0xFFEA580C),
    code: '8998867',
    stock: 180,
    description: 'Mie kuah rasa soto mie gurih segar.',
  ),
  Product(
    id: 'mie-03',
    name: 'Indomie Kuah Ayam Bawang 70g',
    price: 3500,
    wholesalePrice: 3200,
    wholesaleMinQty: 5,
    unit: 'bks',
    categoryId: 'mie_makanan',
    icon: Icons.ramen_dining_rounded,
    color: Color(0xFFEA580C),
    code: '8998868',
    stock: 150,
    description: 'Mie kuah aroma ayam bawang nikmat.',
  ),
  Product(
    id: 'mie-04',
    name: 'Sarimi Isi 2 Goreng Ayam Kremes',
    price: 4500,
    wholesalePrice: 4000,
    wholesaleMinQty: 5,
    unit: 'bks',
    categoryId: 'mie_makanan',
    icon: Icons.lunch_dining_rounded,
    color: Color(0xFFEA580C),
    code: '8998869',
    stock: 90,
    description: 'Porsi dobel puas isi 2 keping mie.',
  ),

  // MINUMAN DINGIN & KOPI SACHET
  Product(
    id: 'mnm-01',
    name: 'Le Minerale Botol Dingin 600ml',
    price: 3500,
    wholesalePrice: 3000,
    wholesaleMinQty: 12,
    unit: 'botol',
    categoryId: 'minuman',
    icon: Icons.local_drink_rounded,
    color: Color(0xFF06B6D4),
    code: '8992770',
    stock: 75,
    description: 'Air mineral pegunungan ada manis-manisnya.',
  ),
  Product(
    id: 'mnm-02',
    name: 'Aqua Botol Dingin 600ml',
    price: 4000,
    wholesalePrice: 3500,
    wholesaleMinQty: 12,
    unit: 'botol',
    categoryId: 'minuman',
    icon: Icons.water_drop_rounded,
    color: Color(0xFF06B6D4),
    code: '8992771',
    stock: 90,
    description: 'Air mineral murni Aqua botol sedang.',
  ),
  Product(
    id: 'mnm-03',
    name: 'Teh Pucuk Harum Dingin 350ml',
    price: 4000,
    wholesalePrice: 3500,
    wholesaleMinQty: 6,
    unit: 'botol',
    categoryId: 'minuman',
    icon: Icons.emoji_food_beverage_rounded,
    color: Color(0xFF06B6D4),
    code: '8992772',
    stock: 60,
    description: 'Teh melati manis segar dari pucuk teh pilihan.',
  ),
  Product(
    id: 'mnm-04',
    name: 'Kopi Kapal Api Spesial Mix (1 Renceng)',
    price: 15000,
    wholesalePrice: 14000,
    wholesaleMinQty: 5,
    unit: 'renceng',
    categoryId: 'minuman',
    icon: Icons.coffee_rounded,
    color: Color(0xFF06B6D4),
    code: '8992773',
    stock: 40,
    description: 'Kopi bubuk + gula sachet isi 10 sachet per renceng.',
  ),
  Product(
    id: 'mnm-05',
    name: 'Kopi Good Day Mocacinno (1 Renceng)',
    price: 16000,
    wholesalePrice: 15000,
    wholesaleMinQty: 5,
    unit: 'renceng',
    categoryId: 'minuman',
    icon: Icons.local_cafe_rounded,
    color: Color(0xFF06B6D4),
    code: '8992774',
    stock: 35,
    description: 'Kopi instan 3-in-1 rasa mocacinno isi 10 sachet.',
  ),

  // BUMBU DAPUR
  Product(
    id: 'bmb-01',
    name: 'Kecap Manis Bango Refill 520ml',
    price: 24000,
    wholesalePrice: 22500,
    wholesaleMinQty: 6,
    unit: 'pouch',
    categoryId: 'bumbu',
    icon: Icons.water_drop_rounded,
    color: Color(0xFF10B981),
    code: '8993001',
    stock: 30,
    description: 'Kecap manis kedelai hitam Mallika kental gurih.',
  ),
  Product(
    id: 'bmb-02',
    name: 'Royco Rasa Ayam (1 Renceng/12 Sachet)',
    price: 6000,
    wholesalePrice: 5500,
    wholesaleMinQty: 5,
    unit: 'renceng',
    categoryId: 'bumbu',
    icon: Icons.soup_kitchen_rounded,
    color: Color(0xFF10B981),
    code: '8993002',
    stock: 50,
    description: 'Bumbu pelezat masakan rasa kaldu ayam asli.',
  ),
  Product(
    id: 'bmb-03',
    name: 'Santan Kelapa Siap Pakai Kara 65ml',
    price: 3500,
    wholesalePrice: 3200,
    wholesaleMinQty: 10,
    unit: 'pcs',
    categoryId: 'bumbu',
    icon: Icons.spa_rounded,
    color: Color(0xFF10B981),
    code: '8993003',
    stock: 80,
    description: 'Santan kelapa murni instan kemasan segitiga.',
  ),

  // ROKOK & TEMBAKAU (Khas Toko Madura / Kelontong)
  Product(
    id: 'rkk-01',
    name: 'Gudang Garam Surya 16 Bungkus',
    price: 36000,
    wholesalePrice: 350000,
    wholesaleMinQty: 10,
    unit: 'bks',
    categoryId: 'rokok',
    icon: Icons.smoking_rooms_rounded,
    color: Color(0xFFEF4444),
    code: '8999901',
    stock: 120,
    description: 'Rokok filter kretek GG Surya isi 16 batang.',
  ),
  Product(
    id: 'rkk-02',
    name: 'Sampoerna A Mild 16 Bungkus',
    price: 35000,
    wholesalePrice: 340000,
    wholesaleMinQty: 10,
    unit: 'bks',
    categoryId: 'rokok',
    icon: Icons.smoking_rooms_rounded,
    color: Color(0xFFEF4444),
    code: '8999902',
    stock: 100,
    description: 'Rokok mild rendah tar dan nikotin isi 16.',
  ),
  Product(
    id: 'rkk-03',
    name: 'Djarum Super 12 Bungkus',
    price: 25000,
    wholesalePrice: 240000,
    wholesaleMinQty: 10,
    unit: 'bks',
    categoryId: 'rokok',
    icon: Icons.smoking_rooms_rounded,
    color: Color(0xFFEF4444),
    code: '8999903',
    stock: 80,
    description: 'Rokok kretek Djarum Super isi 12.',
  ),
  Product(
    id: 'rkk-04',
    name: 'Marlboro Filter Red 20 Bungkus',
    price: 45000,
    wholesalePrice: 440000,
    wholesaleMinQty: 10,
    unit: 'bks',
    categoryId: 'rokok',
    icon: Icons.smoking_rooms_rounded,
    color: Color(0xFFEF4444),
    code: '8999904',
    stock: 50,
    description: 'Rokok putih Marlboro Merah isi 20.',
  ),

  // SABUN & KEBUTUHAN RUMAH
  Product(
    id: 'sbn-01',
    name: 'Sabun Cuci Piring Sunlight Jeruk Nipis 650ml',
    price: 14500,
    wholesalePrice: 13500,
    wholesaleMinQty: 6,
    unit: 'pouch',
    categoryId: 'sabun_rumah',
    icon: Icons.cleaning_services_rounded,
    color: Color(0xFF6366F1),
    code: '8995001',
    stock: 45,
    description: 'Sabun cair pencuci piring ekstrak jeruk nipis asli.',
  ),
  Product(
    id: 'sbn-02',
    name: 'Deterjen Bubuk Daia Bunga 850g',
    price: 18500,
    wholesalePrice: 17500,
    wholesaleMinQty: 6,
    unit: 'bks',
    categoryId: 'sabun_rumah',
    icon: Icons.local_laundry_service_rounded,
    color: Color(0xFF6366F1),
    code: '8995002',
    stock: 35,
    description: 'Deterjen bubuk pembersih pakaian dengan wangi bunga.',
  ),
  Product(
    id: 'sbn-03',
    name: 'Sabun Mandi Lifebuoy Merah Total 10 (4x85g)',
    price: 16000,
    wholesalePrice: 15000,
    wholesaleMinQty: 6,
    unit: 'pack',
    categoryId: 'sabun_rumah',
    icon: Icons.shower_rounded,
    color: Color(0xFF6366F1),
    code: '8995003',
    stock: 40,
    description: 'Sabun batang antibakteri isi 4 pcs.',
  ),

  // GAS LPG & GALON
  Product(
    id: 'gas-01',
    name: 'Isi Ulang Gas LPG 3 Kg (Melon)',
    price: 22000,
    wholesalePrice: 21000,
    wholesaleMinQty: 5,
    unit: 'tabung',
    categoryId: 'gas_galon',
    icon: Icons.propane_tank_rounded,
    color: Color(0xFF0284C7),
    code: '8997001',
    stock: 30,
    description: 'Tukar tabung kosong dengan isi ulang gas elpiji 3kg.',
  ),
  Product(
    id: 'gas-02',
    name: 'Isi Ulang Galon Aqua 19 Liter Asli',
    price: 20000,
    wholesalePrice: 19000,
    wholesaleMinQty: 5,
    unit: 'galon',
    categoryId: 'gas_galon',
    icon: Icons.water_drop_rounded,
    color: Color(0xFF0284C7),
    code: '8997002',
    stock: 25,
    description: 'Tukar galon kosong Aqua 19L segel asli pabrik.',
  ),
  Product(
    id: 'gas-03',
    name: 'Isi Ulang Galon Le Minerale 15L',
    price: 18000,
    wholesalePrice: 17000,
    wholesaleMinQty: 5,
    unit: 'galon',
    categoryId: 'gas_galon',
    icon: Icons.local_drink_rounded,
    color: Color(0xFF0284C7),
    code: '8997003',
    stock: 20,
    description: 'Galon air mineral sekali pakai / isi ulang Le Minerale.',
  ),
];
